server:
#  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# 애플리케이션 포트 설정
# server.port=8080

#MySQL 연결설정
#데이터베이스에 연결하기 위해 mysql jdbc driver 설정
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#연결할 데이터베이스의 url, 포트번호, 데이터베이스 이름 입력
#spring.datasource.url=jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
#데이터베이스를 설치할 때 입력했던 아이디와 비밀번호 입력
#spring.datasource.username=root
#spring.datasource.password=1234

#데이터베이스 초기화 전략 설정
#spring.jpa.hibernate.ddl-auto=create

#JPA가 MySQL8 버전에 맞는 SQL 문법을 사용하도록 설정
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect